openapi: 3.0.2
info:
    title: Library-API
    version: 1.0.0
paths:
    /libraries:
        get:
            tags:
                - libraries
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items: {}
                            examples:
                                List of libraries:
                                    value:
                                        - Mustamäe
                                        - Lasnamäe
                                        - Kopli
                                        - Kristiine
                    description: Library is found
            summary: Get a list of all libraries.
            description: Return a list of all libraries in API.
        post:
            parameters:
                -
                    name: name
                    description: name of book
                    schema:
                        type: string
                    in: query
                    required: true
                -
                    name: genre_name
                    description: genre of book
                    schema:
                        type: string
                    in: query
                    required: true
            responses:
                '201':
                    description: Library has been added
            description: add book
    '/libraries/{id}':
        get:
            tags:
                - id
            parameters:
                -
                    name: id
                    schema:
                        type: array
                        items:
                            type: integer
                    in: path
                    required: true
            responses:
                '200':
                    description: all details of library
                '404':
                    description: library not found
            summary: Get full info of library by ID
            description: Get full info of library by ID
